#!/usr/bin/env python3
import sys

from clinner.command import Type as CommandType, command
from clinner.run import Main

from miner.storj import Miner as StorjMiner


@command(command_type=CommandType.PYTHON,
         args=((('-c', '--config-file'), {'help': 'Config file', 'default': 'config/storj.cfg'}),),
         parser_opts={'help': 'Run Storj miner'})
def start(*args, **kwargs):
    StorjMiner(config=kwargs['config_file']).run()


if __name__ == '__main__':
    sys.exit(Main().run())
